function features = glcm_features(cyan_mask,hemo_mask,eosin_mask)

[Homogeneity_c0, Contrast_c0, Energy_c0,...
Mean_c0, Desvest_c0, Entropy_c0, Correlation_c0] = grayLevelCoocurrenceMatrix(cyan_mask, [2 0]);
% Phase 45 (21)
[Homogeneity_c45, Contrast_c45, Energy_c45,...
Mean_c45, Desvest_c45, Entropy_c45, Correlation_c45] = grayLevelCoocurrenceMatrix(cyan_mask, [-2 2]);

% HEMATOXYLIN. Phase 0 (21)             
[Homogeneity_h0, Contrast_h0, Energy_h0,...
Mean_h0, Desvest_h0, Entropy_h0, Correlation_h0] = grayLevelCoocurrenceMatrix(hemo_mask, [2 0]);      
% Phase 45 (21)
[Homogeneity_h45, Contrast_h45, Energy_h45,...
Mean_h45, Desvest_h45, Entropy_h45, Correlation_h45] = grayLevelCoocurrenceMatrix(hemo_mask, [-2 2]); 

% EOSIN. Phase 0 (21)
[Homogeneity_e0, Contrast_e0, Energy_e0,...
Mean_e0, Desvest_e0, Entropy_e0, Correlation_e0] = grayLevelCoocurrenceMatrix(eosin_mask, [2 0]);  

% Phase 45 (21)
[Homogeneity_e45, Contrast_e45, Energy_e45,...
Mean_e45, Desvest_e45, Entropy_e45, Correlation_e45] = grayLevelCoocurrenceMatrix(eosin_mask, [-2 2]);

features = [
    Homogeneity_c0, Contrast_c0, Energy_c0,...
    Mean_c0, Desvest_c0, Entropy_c0, Correlation_c0,...
    Homogeneity_c45, Contrast_c45, Energy_c45,...
    Mean_c45, Desvest_c45, Entropy_c45, Correlation_c45,...
    Homogeneity_h0, Contrast_h0, Energy_h0,...
    Mean_h0, Desvest_h0, Entropy_h0, Correlation_h0,...
    Homogeneity_h45, Contrast_h45, Energy_h45,...
    Mean_h45, Desvest_h45, Entropy_h45, Correlation_h45,...
    Homogeneity_e0, Contrast_e0, Energy_e0,...
    Mean_e0, Desvest_e0, Entropy_e0, Correlation_e0,...
    Homogeneity_e45, Contrast_e45, Energy_e45,...
    Mean_e45, Desvest_e45, Entropy_e45, Correlation_e45
            ];